### ISSUE TITLE
Eliminate global locks on JIT compilation

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/CLRInstrumentationEngine#33] opened 2018-11-30 20:31 UTC
We are getting reports that Instrumentation Engine shows up on hot path in Application Insights Service Profiler. Like below:

![image](https://user-images.githubusercontent.com/9950081/49313277-9911f800-f49b-11e8-8b8e-ca3d8f906809.png)

@juliusl investigated an issue and believe this is caused by global lock Instrumentation Engine sets on JIT Compilation and other callbacks.

**Comment by SergeyKanzhelev** [comment] 2020-06-11 00:10
Application Insights Service Profiler doesn't use Profiling API. It uses thread stacks sampling to profile application and detected that CLRIE can cause slow down due to global lock.

If you are looking for Intercept extension source code - @cijothomas may help here. See https://github.com/microsoft/CLRInstrumentationEngine/issues/233 where it is requested. I'm not with MS any longer and do not know the current status of this extension open sourcing.

**Comment by delmyers** [comment] 2020-06-11 17:54
@SergeyKanzhelev 

We never actually got your data for this analysis. The graph that you supplied indicates that 4% of the time for this particular trace is spent inside the clrinstrumentation engine, and it doesn't give us any data about what it is doing during that time. 96% of the time is blocked inside EventSource writing, and has nothing to do with ClrInstrumentationEngine.

More than likely, this 4% speed drop was actually caused by calling our logging APIs, and we recently fixed those problems.

This is an old bug, @juliusl do you have data to back up the idea that the slow down is caused by the global lock? I have my doubts about that.

**Comment by SergeyKanzhelev** [comment] 2020-06-14 03:01
@delmyers it is possible that the issue was in logging. I don't remember the history and most probably it was a screenshot without a clear repro. Feel free to close the issue.

**Comment by delmyers** [comment] 2020-06-15 16:24
@sanikolov, it looks like this particular issue doesn't have a repro. We are going to close it. Feel free to open up another discussion issue with us to talk about app insights compatibility, if you like.

**Closed by delmyers** 2020-06-15 16:24 UTC
